[package]
name = "tmuxify"
version = "0.1.0"
authors = ["Jonathan Rothberg <jonnyrpi@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
clap = { git = "https://github.com/clap-rs/clap/" }
